import type { CatalogResponse } from './catalog.types.js';

export const seedCatalog: CatalogResponse = {
  categories: [
    { id: 'tapiocas-doces', name: 'Tapiocas Doces', sortOrder: 1 },
    { id: 'tapiocas-salgadas', name: 'Tapiocas Salgadas', sortOrder: 2 },
    { id: 'pasteis-doces', name: 'Pastéis Doces', sortOrder: 3 },
    { id: 'pasteis-salgados', name: 'Pastéis Salgados', sortOrder: 4 },
    { id: 'batata-recheada', name: 'Batata Recheada', sortOrder: 5 },
    { id: 'porcoes', name: 'Porções', sortOrder: 6 },
    { id: 'bolos-e-sobremesas', name: 'Bolos e Sobremesas', sortOrder: 7 },
    { id: 'bebidas', name: 'Bebidas', sortOrder: 8 },
  ],
  items: [
    {
      id: 'tapioca-doce-creme-de-avela',
      name: 'Creme de Avelã',
      description: 'Tapioca doce com creme de avelã (puro).',
      priceCents: 1200,
      categoryId: 'tapiocas-doces',
      categoryName: 'Tapiocas Doces',
      imageUrl: '/images/tapiocafrango.jpeg',
      available: true,
    },
    {
      id: 'tapioca-doce-morango-com-chocolate',
      name: 'Morango com Chocolate',
      description: 'Tapioca doce com morango e chocolate meio amargo.',
      priceCents: 1400,
      categoryId: 'tapiocas-doces',
      categoryName: 'Tapiocas Doces',
      imageUrl: '/images/tapiocafrango.jpeg',
      available: true,
    },
    {
      id: 'tapioca-salgada-frango-com-requeijao',
      name: 'Frango com Requeijão',
      description: 'Tapioca salgada de frango com requeijão cremoso.',
      priceCents: 1500,
      categoryId: 'tapiocas-salgadas',
      categoryName: 'Tapiocas Salgadas',
      imageUrl: '/images/tapiocafrango.jpeg',
      available: true,
    },
    {
      id: 'tapioca-salgada-carne-seca',
      name: 'Carne Seca com Queijo',
      description: 'Tapioca salgada de carne seca com queijo coalho.',
      priceCents: 1700,
      categoryId: 'tapiocas-salgadas',
      categoryName: 'Tapiocas Salgadas',
      imageUrl: '/images/tapiocafrango.jpeg',
      available: true,
    },
    {
      id: 'pastel-salgado-carne-com-queijo',
      name: 'Carne com Queijo',
      description: 'Pastel salgado de carne com queijo.',
      priceCents: 1100,
      categoryId: 'pasteis-salgados',
      categoryName: 'Pastéis Salgados',
      imageUrl: '/images/pastel.jpeg',
      available: true,
    },
    {
      id: 'pastel-salgado-frango-catupiry',
      name: 'Frango com Catupiry',
      description: 'Pastel salgado de frango com Catupiry original.',
      priceCents: 1100,
      categoryId: 'pasteis-salgados',
      categoryName: 'Pastéis Salgados',
      imageUrl: '/images/pastel.jpeg',
      available: true,
    },
    {
      id: 'pastel-doce-romeu-e-julieta',
      name: 'Romeu e Julieta',
      description: 'Pastel doce de queijo com goiabada.',
      priceCents: 1000,
      categoryId: 'pasteis-doces',
      categoryName: 'Pastéis Doces',
      imageUrl: '/images/pastel.jpeg',
      available: true,
    },
    {
      id: 'batata-recheada-frango',
      name: 'Frango com Requeijão (Batata)',
      description: 'Batata recheada com frango desfiado e requeijão.',
      priceCents: 1800,
      categoryId: 'batata-recheada',
      categoryName: 'Batata Recheada',
      imageUrl: '/images/Background2tapiocas.jpeg',
      available: true,
    },
    {
      id: 'batata-recheada-strogonoff',
      name: 'Strogonoff de Carne (Batata)',
      description: 'Batata recheada com strogonoff de carne suculento.',
      priceCents: 2200,
      categoryId: 'batata-recheada',
      categoryName: 'Batata Recheada',
      imageUrl: '/images/Background2tapiocas.jpeg',
      available: true,
    },
    {
      id: 'porcao-fritas-simples',
      name: 'Batata Frita (P)',
      description: 'Porção de batata frita crocante.',
      priceCents: 1500,
      categoryId: 'porcoes',
      categoryName: 'Porções',
      imageUrl: '/images/Logo_Sabor_Real-removebg-preview.png',
      available: true,
    },
    {
      id: 'sobremesa-fatia-de-pudim',
      name: 'Fatia de Pudim',
      description: 'Fatia de pudim de leite condensado caseiro.',
      priceCents: 1000,
      categoryId: 'bolos-e-sobremesas',
      categoryName: 'Bolos e Sobremesas',
      imageUrl: '/images/pudimPedaco.jpeg',
      available: true,
    },
    {
      id: 'bebida-refrigerante-lata',
      name: 'Refrigerante Lata',
      description: 'Coca-Cola, Guaraná, Fanta (especificar sabor).',
      priceCents: 600,
      categoryId: 'bebidas',
      categoryName: 'Bebidas',
      imageUrl: '/images/Logo_Sabor_Real-removebg-preview.png',
      available: true,
    },
    {
      id: 'bebida-suco-natural',
      name: 'Suco Natural',
      description: 'Suco de laranja ou limão (500ml).',
      priceCents: 800,
      categoryId: 'bebidas',
      categoryName: 'Bebidas',
      imageUrl: '/images/Logo_Sabor_Real-removebg-preview.png',
      available: true,
    },
  ],
};
